# **Practical 10**

# **(1) Implementation of LSTM on Gold Price Prediction**

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler

In [ ]:
data=pd.read_csv("/content/drive/MyDrive/datasets/datasets/Train_GoldPrice_RNN.csv")

In [ ]:
data

Date  Close/Last    Volume    Open    High     Low
0     04/18/2024      2398.0  195493.0  2377.9  2408.0  2377.2
1     04/17/2024      2388.4  279551.0  2398.0  2412.0  2370.7
2     04/16/2024      2407.8  290700.0  2399.1  2414.8  2379.2
3     04/15/2024      2383.0  336608.0  2369.4  2404.3  2340.2
4     04/12/2024      2374.1  463075.0  2389.4  2448.8  2350.6
...          ...         ...       ...     ...     ...     ...
1253  04/26/2019      1288.8  268033.0  1279.1  1290.9  1276.0
1254  04/25/2019      1279.7  230543.0  1277.9  1284.8  1275.2
1255  04/24/2019      1279.4  235966.0  1274.4  1280.7  1270.5
1256  04/23/2019      1273.2  271377.0  1277.0  1278.5  1267.9
1257  04/22/2019      1277.6  133327.0  1278.0  1281.9  1275.7

[1258 rows x 6 columns]

In [ ]:
data.head()

Date  Close/Last    Volume    Open    High     Low
0  04/18/2024      2398.0  195493.0  2377.9  2408.0  2377.2
1  04/17/2024      2388.4  279551.0  2398.0  2412.0  2370.7
2  04/16/2024      2407.8  290700.0  2399.1  2414.8  2379.2
3  04/15/2024      2383.0  336608.0  2369.4  2404.3  2340.2
4  04/12/2024      2374.1  463075.0  2389.4  2448.8  2350.6

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1258 entries, 0 to 1257
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Date        1258 non-null   object 
 1   Close/Last  1258 non-null   float64
 2   Volume      1254 non-null   float64
 3   Open        1258 non-null   float64
 4   High        1258 non-null   float64
 5   Low         1258 non-null   float64
dtypes: float64(5), object(1)
memory usage: 59.1+ KB


In [ ]:
data.isnull().sum()

Date          0
Close/Last    0
Volume        4
Open          0
High          0
Low           0
dtype: int64

In [ ]:
data=data.dropna()

In [ ]:
data.isnull().sum()

Date          0
Close/Last    0
Volume        0
Open          0
High          0
Low           0
dtype: int64

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1254 entries, 0 to 1257
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Date        1254 non-null   object 
 1   Close/Last  1254 non-null   float64
 2   Volume      1254 non-null   float64
 3   Open        1254 non-null   float64
 4   High        1254 non-null   float64
 5   Low         1254 non-null   float64
dtypes: float64(5), object(1)
memory usage: 68.6+ KB


In [ ]:
data1=data.iloc[:,3:4].values

In [ ]:
train_data=data1[:int(len(data1)*0.75)]
test_data=data1[len(train_data):]

In [ ]:
train_data

array([[2377.9],
       [2398. ],
       [2399.1],
       [2369.4],
       [2389.4],
       [2351.7],
       [2372.4],
       [2358.1],
       [2343.6],
       [2309.5],
       [2321. ],
       [2301.7],
       [2272.7],
       [2259.2],
       [2215.7],
       [2200.5],
       [2173. ],
       [2166.6],
       [2183.4],
       [2190.2],
       [2161.4],
       [2164. ],
       [2159.9],
       [2166.2],
       [2179.5],
       [2163.6],
       [2189.1],
       [2187.6],
       [2166.6],
       [2156.7],
       [2136.4],
       [2123.3],
       [2091.6],
       [2052.8],
       [2043.8],
       [2039.7],
       [2041.2],
       [2044.2],
       [2034.1],
       [2036.5],
       [2036.2],
       [2027.7],
       [2016.1],
       [2004.8],
       [2006.3],
       [2033.7],
       [2038.2],
       [2049.7],
       [2051. ],
       [2052.6],
       [2041.4],
       [2057.9],
       [2072. ],
       [2057.9],
       [2055.3],
       [2051.5],
       [2024.4],
       [2021. ],
       [2014.8

In [ ]:
test_data

array([[1812.3],
       [1796.9],
       [1813.1],
       [1811.1],
       [1810.9],
       [1803.4],
       [1808.4],
       [1818.8],
       [1807.9],
       [1793.9],
       [1787. ],
       [1779. ],
       [1798.9],
       [1799.2],
       [1789.2],
       [1774.8],
       [1772.3],
       [1784.4],
       [1764.9],
       [1765.8],
       [1729.8],
       [1735.5],
       [1735.3],
       [1732.3],
       [1740.7],
       [1733.6],
       [1746.6],
       [1718.9],
       [1703.9],
       [1686.7],
       [1720.8],
       [1702.8],
       [1733.7],
       [1750.3],
       [1749.8],
       [1718.8],
       [1725. ],
       [1724.1],
       [1746.3],
       [1726.6],
       [1751.7],
       [1751.6],
       [1734.8],
       [1757.5],
       [1739.7],
       [1723.1],
       [1705. ],
       [1700. ],
       [1706. ],
       [1726.2],
       [1686. ],
       [1714.1],
       [1711. ],
       [1711.2],
       [1686.6],
       [1729.6],
       [1710. ],
       [1724.4],
       [1745. 

In [ ]:


train_data=train_data.reshape(-1,1)

In [ ]:
test_data=test_data.reshape(-1,1)

In [ ]:
train_data

array([[2377.9],
       [2398. ],
       [2399.1],
       [2369.4],
       [2389.4],
       [2351.7],
       [2372.4],
       [2358.1],
       [2343.6],
       [2309.5],
       [2321. ],
       [2301.7],
       [2272.7],
       [2259.2],
       [2215.7],
       [2200.5],
       [2173. ],
       [2166.6],
       [2183.4],
       [2190.2],
       [2161.4],
       [2164. ],
       [2159.9],
       [2166.2],
       [2179.5],
       [2163.6],
       [2189.1],
       [2187.6],
       [2166.6],
       [2156.7],
       [2136.4],
       [2123.3],
       [2091.6],
       [2052.8],
       [2043.8],
       [2039.7],
       [2041.2],
       [2044.2],
       [2034.1],
       [2036.5],
       [2036.2],
       [2027.7],
       [2016.1],
       [2004.8],
       [2006.3],
       [2033.7],
       [2038.2],
       [2049.7],
       [2051. ],
       [2052.6],
       [2041.4],
       [2057.9],
       [2072. ],
       [2057.9],
       [2055.3],
       [2051.5],
       [2024.4],
       [2021. ],
       [2014.8

In [ ]:
scale = MinMaxScaler()
scaled_train=scale.fit_transform(train_data)

In [ ]:
scale = MinMaxScaler()
scaled_test=scale.fit_transform(test_data)

In [ ]:
scaled_train

array([[0.97246396],
       [0.99857124],
       [1.        ],
       [0.96142356],
       [0.98740096],
       [0.93843356],
       [0.96532017],
       [0.94674633],
       [0.92791272],
       [0.88362125],
       [0.89855825],
       [0.87349006],
       [0.83582283],
       [0.81828809],
       [0.76178725],
       [0.74204442],
       [0.7063255 ],
       [0.69801273],
       [0.71983374],
       [0.72866606],
       [0.69125861],
       [0.69463567],
       [0.6893103 ],
       [0.69749318],
       [0.71476815],
       [0.69411612],
       [0.7272373 ],
       [0.725289  ],
       [0.69801273],
       [0.68515392],
       [0.65878686],
       [0.64177166],
       [0.60059748],
       [0.55020132],
       [0.53851149],
       [0.53318613],
       [0.53513443],
       [0.53903104],
       [0.52591246],
       [0.52902974],
       [0.52864008],
       [0.51759969],
       [0.5025328 ],
       [0.48785557],
       [0.48980387],
       [0.52539291],
       [0.53123782],
       [0.546

In [ ]:
X_train=[]
y_train=[]

for i in range(50,len(scaled_train)):
  X_train.append(scaled_train[i-50:i,0])
  y_train.append(scaled_train[i,0])

X_train=np.array(X_train)
y_train=np.array(y_train)

In [ ]:


X_test=[]
y_test=[]

for i in range(50,len(scaled_test)):
  X_test.append(scaled_test[i-50:i,0])
  y_test.append(scaled_test[i,0])

X_test=np.array(X_test)
y_test=np.array(y_test)

In [ ]:
X_train


array([[0.97246396, 0.99857124, 1.        , ..., 0.54617483, 0.54786336,
        0.54994155],
       [0.99857124, 1.        , 0.96142356, ..., 0.54786336, 0.54994155,
        0.53539421],
       [1.        , 0.96142356, 0.98740096, ..., 0.54994155, 0.53539421,
        0.55682556],
       ...,
       [0.36602156, 0.34030394, 0.35589038, ..., 0.43382257, 0.38940122,
        0.33212105],
       [0.34030394, 0.35589038, 0.33406936, ..., 0.38940122, 0.33212105,
        0.31484608],
       [0.35589038, 0.33406936, 0.30328614, ..., 0.33212105, 0.31484608,
        0.27743863]])

In [ ]:

X_train.shape

(890, 50)

In [ ]:
y_train.shape

(890,)

In [ ]:
X_test.shape


(264, 50)

In [ ]:

y_test.shape

(264,)

In [ ]:

model = keras.Sequential([
    keras.layers.LSTM(200, activation="tanh", input_shape=(50, 1), return_sequences=False),
    keras.layers.Dense(100, activation="relu"),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(1, activation="linear")
])

In [ ]:
model.compile(optimizer="adam", loss="mse",metrics="accuracy")

In [ ]:
model.fit(X_train, y_train, epochs=50, batch_size=32)

Epoch 1/50
28/28 [==============================] - 6s 125ms/step - loss: 0.0117 - accuracy: 0.0011
Epoch 2/50
28/28 [==============================] - 3s 107ms/step - loss: 0.0029 - accuracy: 0.0011
Epoch 3/50
28/28 [==============================] - 3s 108ms/step - loss: 0.0023 - accuracy: 0.0011
Epoch 4/50
28/28 [==============================] - 2s 86ms/step - loss: 0.0021 - accuracy: 0.0011
Epoch 5/50
28/28 [==============================] - 3s 92ms/step - loss: 0.0021 - accuracy: 0.0011
Epoch 6/50
28/28 [==============================] - 3s 119ms/step - loss: 0.0019 - accuracy: 0.0011
Epoch 7/50
28/28 [==============================] - 2s 77ms/step - loss: 0.0021 - accuracy: 0.0011
Epoch 8/50
28/28 [==============================] - 2s 78ms/step - loss: 0.0017 - accuracy: 0.0011
Epoch 9/50
28/28 [==============================] - 2s 78ms/step - loss: 0.0020 - accuracy: 0.0011
Epoch 10/50
28/28 [==============================] - 2s 77ms/step - loss: 0.0019 - accuracy: 0.0011
Epoch

In [ ]:
model.evaluate(X_test,y_test)

9/9 [==============================] - 1s 28ms/step - loss: 0.0018 - accuracy: 0.0038


[0.0017591669457033277, 0.0037878789007663727]