# **Practical 9**

# **Implementation of RNN on Stock Market Price Pridiction**

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler


In [ ]:
Training_data = pd.read_csv("/content/drive/MyDrive/datasets/datasets/Train_RNN.csv")

In [ ]:
Test_data = pd.read_csv("/content/drive/MyDrive/datasets/datasets/Test_RNN.csv")

In [ ]:
Training_data.head()

Date        Open        High         Low       Close   Adj Close  \
0  2023-04-10  107.389999  107.970001  105.599998  106.949997  106.949997   
1  2023-04-11  106.919998  107.220001  105.279999  106.120003  106.120003   
2  2023-04-12  107.389999  107.586998  104.970001  105.220001  105.220001   
3  2023-04-13  106.470001  108.264999  106.440002  108.190002  108.190002   
4  2023-04-14  107.690002  109.580002  107.589996  109.459999  109.459999   

     Volume  
0  19741500  
1  18721300  
2  22761600  
3  21650700  
4  20758700

In [ ]:
Test_data.head()

Date       Open       High        Low      Close  Adj Close    Volume
0  2021-01-11  89.303497  89.715752  88.026001  88.335999  88.335999  24194000
1  2021-01-12  87.695999  88.902000  86.265503  87.327499  87.327499  27140000
2  2021-01-13  86.929001  88.251747  86.900497  87.720001  87.720001  21882000
3  2021-01-14  87.681000  88.750504  86.669998  87.009003  87.009003  23590000
4  2021-01-15  86.909500  87.800003  86.077499  86.809502  86.809502  26844000

In [ ]:
Training_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 252 entries, 0 to 251
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Date       252 non-null    object 
 1   Open       252 non-null    float64
 2   High       252 non-null    float64
 3   Low        252 non-null    float64
 4   Close      252 non-null    float64
 5   Adj Close  252 non-null    float64
 6   Volume     252 non-null    int64  
dtypes: float64(5), int64(1), object(1)
memory usage: 13.9+ KB


In [ ]:
training_data=Training_data.iloc[:,1:2].values

In [ ]:
testing_data=Test_data.iloc[:,1:2].values

In [ ]:
training_data.shape,Training_data.shape

((252, 1), (252, 7))

In [ ]:
testing_data.shape,Test_data.shape

((816, 1), (816, 7))

In [ ]:
training_data[:5]

array([[107.389999],
       [106.919998],
       [107.389999],
       [106.470001],
       [107.690002]])

In [ ]:
sc=MinMaxScaler()
scaled_train_data=sc.fit_transform(training_data)

In [ ]:
scaled_train_data[:5]

array([[0.0597535 ],
       [0.05090809],
       [0.0597535 ],
       [0.04243916],
       [0.06539955]])

In [ ]:
sc=MinMaxScaler()
scaled_test_data=sc.fit_transform(testing_data)

In [ ]:
scaled_test_data[:5]

array([[0.05280477],
       [0.03042869],
       [0.01975221],
       [0.0302199 ],
       [0.01948076]])

**Creating dataset for price prediction**

In [ ]:
X_train=[]
y_train=[]

for i in range(50,225):
  X_train.append(scaled_train_data[i-50:i,0])
  y_train.append(scaled_train_data[i,0])

X_train=np.array(X_train)
y_train=np.array(y_train)

In [ ]:
X_test=[]
y_test=[]

for i in range(50,225):
  X_test.append(scaled_test_data[i-50:i,0])
  y_test.append(scaled_test_data[i,0])

X_test=np.array(X_test)
y_test=np.array(y_test)

In [ ]:
X_train.shape,y_train.shape

((175, 50, 1), (175,))

In [ ]:
X_train=X_train.reshape(175,50,1)

In [ ]:
X_train.shape

(175, 50, 1)

In [ ]:
model = keras.Sequential([keras.layers.SimpleRNN(100, activation="relu", input_shape=(50,1), return_sequences=False),
                          keras.layers.Dense(1, activation = "linear")])

In [ ]:
model.compile(optimizer="adam", loss="mse")

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 100)               10200     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 10,301
Trainable params: 10,301
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(X_train, y_train, epochs=100, batch_size=32)

Epoch 1/100
6/6 [==============================] - 3s 16ms/step - loss: 0.2281
Epoch 2/100
6/6 [==============================] - 0s 17ms/step - loss: 0.0230
Epoch 3/100
6/6 [==============================] - 0s 15ms/step - loss: 0.0119
Epoch 4/100
6/6 [==============================] - 0s 16ms/step - loss: 0.0054
Epoch 5/100
6/6 [==============================] - 0s 17ms/step - loss: 0.0058
Epoch 6/100
6/6 [==============================] - 0s 18ms/step - loss: 0.0050
Epoch 7/100
6/6 [==============================] - 0s 14ms/step - loss: 0.0043
Epoch 8/100
6/6 [==============================] - 0s 19ms/step - loss: 0.0039
Epoch 9/100
6/6 [==============================] - 0s 14ms/step - loss: 0.0040
Epoch 10/100
6/6 [==============================] - 0s 14ms/step - loss: 0.0040
Epoch 11/100
6/6 [==============================] - 0s 14ms/step - loss: 0.0037
Epoch 12/100
6/6 [==============================] - 0s 14ms/step - loss: 0.0038
Epoch 13/100
6/6 [==============================]

In [ ]:
model.evaluate(X_test,y_test)

6/6 [==============================] - 0s 6ms/step - loss: 0.5920


0.592029869556427